### ISSUE TITLE
怎么不能够切换方案的么?

### ISSUE THREAD

**Issue by hubutui** [guoyunhe/font-config-master#22]
我的意思是, 比如我想修改之前的方案, 选中之后, 界面显示的字体设置还是之前的方案的.

**Comment by guoyunhe** [comment]
已修复。之前不能够在切换配置方案后读取配置方案文件，也没有保存修改。现在在切换配置方案的时候：
1. 保存上一个配置方案。
2. 加载下一个配置方案。

只有点击**确定**的时候，才会将配置方案应用到系统设置。而如果点击取消，下次运行程序时，当前配置方案会恢复到与系统实际的配置同步。
