### ISSUE TITLE
lxqt-config-appearance 会覆盖 ~/.config/fontconfig/fonts.conf

### ISSUE THREAD

**Issue by hubutui** [guoyunhe/font-config-master#23]
lxqt-config-appearance 配置字体也会覆盖 ~/.config/fontconfig/fonts.conf 这个文件. 能不能换成别的文件? 比如  ~/.config/fontconfig/conf.d 目录下的?

**Comment by guoyunhe** [comment]
这样做并不能解决问题，因为  `~/.config/fontconfig/fonts.conf` 的优先级高于 `~/.config/fontconfig/conf.d` ，最后还是被 lxqt-config-appearance 的设置覆盖。

配置前端工具的原则应该是 **尊重已有的设置** ，即不抹除其它工具设定的配置项。比如 KDE 字体设置只能设置抗锯齿，不能设置 font-family ，但 KDE 在修改配置文件时会保留这些内容，不与其它软件冲突。

这个问题应该是 lxqt-config-appearance 的特定行为。有很多用户是手动修改 `~/.config/fontconfig/fonts.conf` 的，如果会被 lxqt-config-appearance 覆写，那说明是 lxqt-config-appearance 的设计问题。

**Comment by hubutui** [comment]
如果不打开 lxqt-config-appearance 进行配置的话, 配置文件就不会被覆盖, 所以就不会有冲突了. 后来才发现了, 不过能够自己备份一下配置文件更好, fontweak 已经给备份了啊.

**Comment by guoyunhe** [comment]
fontweak 的每个配置方案在 `.config/fontweak/schemes/` 文件夹下面保存一个副本。

为了照顾有些用户可能手动修改 `.config/fontconfig/fonts.conf` 或使用了其它工具，比如 KDE 字体配置，每次启动 fontweak 时都会读取新 `.config/fontconfig/fonts.conf` ，如果有修改则会覆盖 fontweak 的当前配置方案。所以当前配置方案总是会受到外部修改的影响。

如果其它工具保留了 fontweak 才有的设置，就像 KDE 字体设置，则 fontweak 仍能够得到之前设置的大部分，只有少部分被有意的修改了。fontweak 和 KDE 字体设置是相互兼容的。

反之，如果其他工具清除了 fontweak 才有的设置，那么 fontweak 的当前配置方案就永久性地丢失了那些设置。这说明 fontweak 和 lxqt-config-appearance 是不兼容的。建议两者不要一起使用，或者在 fontweak 中为当前配置方案手动建一个备份的配置方案，比如“Current_Backup”。

我也考虑过其他解决方法。假设当前配置方案是 **Favorite** 每次启动 fontweak 时，比较 `.config/fontconfig/fonts.conf` 和当前配置方案是否有不同。如果相同，则导入当前配置方案；如果不同，则创建并切换到新方案 **Favorite_modified**。如果用户喜欢新方案，就保持原样好了。如果用户想回到原来的方案，像你这种情况，可以删除新配置方案 **Favorite_modified** 切换到老的配置方案 **Favorite**。
