### ISSUE TITLE
无法恢复到系统默认的字体配置

### ISSUE THREAD

**Issue by bruceauyeung** [guoyunhe/font-config-master#27]
1，点击一键设置 ->确定。
2，我发现和我原来的配置没有区别，就点击了重置系统默认->确定。
3，注销重新登录，发现整个系统的字体显示变成这个样子了。
![9](https://cloud.githubusercontent.com/assets/1210201/12293805/ee4df272-ba30-11e5-9d8b-78c550a2bdaf.png)
而原来是这样子的。
![8](https://cloud.githubusercontent.com/assets/1210201/12293816/051bdc08-ba31-11e5-9c9c-e46dc7043cd1.png)

与此同时，Opera，Chrome 这些浏览器，会变得异常卡顿。当然，这个是由于Chrome的一个bug引发的。参见
https://forum.suse.org.cn/viewtopic.php?f=5&t=3677

而且，最大化、恢复窗口大小会出现严重的窗口闪烁。
fontweak 0.6.1
openSUSE Leap 42.1

**Comment by guoyunhe** [comment]
可能是重制系统设置的 Antialias 搞错了。

**Comment by bruceauyeung** [comment]
我现在是只能用fontweak的一键设置恢复成原来的配置了。但是opera会卡顿，应该是gtk程序用到了有中文名称的无衬线字体导致的。关键是我还无能为力了。

**Comment by guoyunhe** [comment]
不大清楚 GTK 程序为何会有故障，因为后端 fontconfig 是比 GTK/GNOME 或者 Qt/KDE 设置更底层的。大概是 GTK 或者 Opera 的问题吧。应该只能期待 fontconfig, GTK 和 Opera 的开发者解决这个问题了

**Comment by bruceauyeung** [comment]
我把 `～/.config/fontconfig` 目录删除之后，字体恢复成原来的了（GTK程序的字体，包括页面字体却并没有恢复），但是 Opera 依旧卡顿，当 GTK 字体换成 Noto Sans 之后（我原来用的是 Droid Sans Fallback,你的一键设置里面用的也是这个字体）就不卡了，我想问是不是还有其它的地方你做了修改，比如设置了把Droid Sans Fallback设置了别名 无衬线？

**Comment by guoyunhe** [comment]
所有修改都在 `～/.config/fontconfig` 内，字体别名并没有无衬线的设置。

Droid Sans Fallback 实际是一种中文字体，而 Noto Sans 是西文字体。

Fontweak 生成的每一个 XML 文件都是按照 fontconfig 规范的。如果你删除了 ～/.config/fontconfig 问题依旧存在，说明那是 GTK 设置的问题或者 Opera 的问题。

**Comment by bruceauyeung** [comment]
可是我GTK之前就设置的Droid Sans Fallback，一切正常，现在设为这个字体就卡了，只能设置为 其它无中文名称的字体比如Noto Sans。
Chrome/Opera在字体显示是有问题（[Linux 系统中 Chrome 地址栏输入卡顿的解决方法](http://suselinks.us/how-to-fix-slow-typing-in-chrome-addressbar-in-linux/)），但是可以通过设置字体来规避。
![10](https://cloud.githubusercontent.com/assets/1210201/12294624/e10b76b0-ba36-11e5-86fe-fb4c50d62510.png)

**Comment by guoyunhe** [comment]
这个问题不在 fontconfig 配置文件的控制范围内了。你可以向 GTK 或者 Opera 反映这个 bug 。我就无能为力了。

**Comment by guoyunhe** [comment]
已在新版本中修复。应该说是把这个一键设置功能去掉了……
