### ISSUE TITLE
not a bug

### ISSUE THREAD

**Issue by grenzionky** [guoyunhe/font-config-master#34]
this isnt a bug, i just wanted to tell you how amazing your program is!!! ive been stuck in wrong fonts hell for the last couple months and no amount of research/tinkering/manual reading was able to solve it… until i came across ur program, and u solved it instantly!!!! 🤯 so thank you so much for creating it! 🤗

**Comment by guoyunhe** [comment]
Thanks! i haven't been updating it for a long long time. Here is a plan to add more functionality and use Qt/GTK front-end instead of out-dated Java Swing.
